name: 'CI/CD Pipeline'
on: [push]

env:
  PYTHON_OUTPUT: ''

jobs:
  Test:
      name: Testing
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Run Python Script
        run: python hello.py > ${{env.PYTHON_OUTPUT}}
  
  Build:
      name: Build
      runs-on: ubuntu-latest
      needs: [Test]
      
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create an artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./${{env.PYTHON_OUTPUT}}
