name: 
on: push

env:
  WORKPLACE_NAME: 'MontyMangos Fast Food Company'

jobs:
  one-job-two-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.WORKPLACE_NAME }}
