name: Challenge_1

on: [issues]

jobs:
  Ubuntu:
    name: Ubuntu latest
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date
  
  Windows:
    name: Windows latest
    runs-on: windows-latest
    steps:
      - name: Get-Date
        run: Get-Date
  
  MacOS:
    name: MacOS latest
    runs-on: macos-latest
    steps:
      - name: print date
        run: date

  MacOSMonterey:
    name: MacOS 12 Monterey
    runs-on: macos-12
    needs: [Ubuntu, Windows, MacOS] 
    steps:
      - name: print date
        run: date
