name: 'CI/CD Pipeline'
on: [push]

jobs:
  Test:
      name: Testing
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Run Python Script
        run: python hello.py > hello_output
  
  Build:
      name: Build
      runs-on: ubuntu-latest
      needs: [Test]
      
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create an artifact
        env: 
          PYTHON_OUTPUT: 'hello_output'
